### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by briecoyle** [learn-co/learn-ide-tree#20] opened 2016-12-12 17:53 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 2.2.0
**Electron Version**: 1.3.6
**System**: Mac OS X 10.12.1
**Thrown From**: [learn-ide-tree](https://github.com/learn-co/learn-ide-tree) package, v1.0.17

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /private/var/folders/hb/qc3cv9wn5v19pgkty_sr9v_00000gp/T/AppTranslocation/CD9D4BA4-123B-4F2B-BC24-6D841BDE442A/d/Learn IDE 2.app/Contents/Resources/app.asar/node_modules/learn-ide-tree/lib/nsync/initializer.js:69

TypeError: Cannot read property 'getPath' of undefined
    at atom-workspace.onSave (/private/var/folders/hb/qc3cv9wn5v19pgkty_sr9v_00000gp/T/AppTranslocation/CD9D4BA4-123B-4F2B-BC24-6D841BDE442A/d/Learn IDE 2.app/Contents/Resources/app.asar/node_modules/learn-ide-tree/lib/nsync/initializer.js:69:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/private/var/folders/hb/qc3cv9wn5v19pgkty_sr9v_00000gp/T/AppTranslocation/CD9D4BA4-123B-4F2B-BC24-6D841BDE442A/d/Learn IDE 2.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /private/var/folders/hb/qc3cv9wn5v19pgkty_sr9v_00000gp/T/AppTranslocation/CD9D4BA4-123B-4F2B-BC24-6D841BDE442A/d/Learn IDE 2.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/private/var/folders/hb/qc3cv9wn5v19pgkty_sr9v_00000gp/T/AppTranslocation/CD9D4BA4-123B-4F2B-BC24-6D841BDE442A/d/Learn IDE 2.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:584:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/private/var/folders/hb/qc3cv9wn5v19pgkty_sr9v_00000gp/T/AppTranslocation/CD9D4BA4-123B-4F2B-BC24-6D841BDE442A/d/Learn IDE 2.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:379:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/hb/qc3cv9wn5v19pgkty_sr9v_00000gp/T/AppTranslocation/CD9D4BA4-123B-4F2B-BC24-6D841BDE442A/d/Learn IDE 2.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/private/var/folders/hb/qc3cv9wn5v19pgkty_sr9v_00000gp/T/AppTranslocation/CD9D4BA4-123B-4F2B-BC24-6D841BDE442A/d/Learn IDE 2.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -2:08.0 tree-view:toggle (atom-text-editor.editor.is-focused)
  2x -0:03.2.0 learn-ide:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "integrated-learn-environment"
    ],
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (inactive)
integrated-learn-environment, v1.9.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.1 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
update-package-dependencies, v0.10.0 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)
learn-ide, v2.2.0 (active)
learn-ide-tree, v1.0.17 (active)

# Dev
No dev packages
```

**Comment by Curious-Yu** [comment] 2016-12-19 05:01
I have the same problem too. How to get it fix? Many thanks.

**Comment by aaronrtrevino12** [comment] 2016-12-21 21:10
Using Windows 10.  Begins when I find out I can't type anything into the console.  I then try to save and close any open files before closing Learn IDE so I can reopen.  I get the error while trying to save a file.  Did not have this issue with Learn IDE 1.9.  I've uninstalled Learn IDE 2.0 and reinstalled.  Also rebooted many times.  Sometimes Learn IDE opens two windows, instead of one window.  Before I reinstalled Learn IDE it would open up to three windows.

**Comment by aaronrtrevino12** [comment] 2016-12-21 21:41
See following.  Thanks!

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 2.2.1
**Electron Version**: 1.3.6
**System**: Microsoft Windows 10 Home
**Thrown From**: [learn-ide-tree](https://github.com/learn-co/learn-ide-tree) package, v1.0.17


### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At C:\Users\Aaron\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\node_modules\learn-ide-tree\lib\nsync\initializer.js:69

TypeError: Cannot read property 'getPath' of undefined
    at atom-workspace.onSave (C:\Users\Aaron\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\node_modules\learn-ide-tree\lib\nsync\initializer.js:69:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Aaron\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Aaron\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Aaron\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\Aaron\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\atom-environment.js:1136:28)
    at EventEmitter.outerCallback (C:\Users\Aaron\AppData\Local\learn_ide\app-2.2.1\resources\app.asar\src\application-delegate.js:319:25)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

### Commands

```
     -8:45.8.0 tree-view:rename (li.texteditor.tab.sortable.pending-tab.active.right-clicked)
     -8:42.6.0 core:delete (atom-text-editor.editor.mini.is-focused)
 18x -8:39.7.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -8:36.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.1.0 learn-ide:save (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "integrated-learn-environment"
    ]
  },
  "learn-ide-tree": {
    "hideVcsIgnoredFiles": true
  }
}
```

### Installed Packages

```coffee
# User
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.1 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
update-package-dependencies, v0.10.0 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)
learn-ide, v2.2.1 (active)
learn-ide-tree, v1.0.17 (active)

# Dev
No dev packages
```

**Comment by sjwakeman** [comment] 2016-12-26 23:14
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 2.1.0
**Electron Version**: 1.3.6
**System**: Microsoft Windows 10 Home
**Thrown From**: [learn-ide-tree](https://github.com/learn-co/learn-ide-tree) package, v1.0.17


### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At C:\Users\SWAKE\AppData\Local\learn_ide\app-2.1.0\resources\app.asar\node_modules\learn-ide-tree\lib\nsync\initializer.js:69

TypeError: Cannot read property 'getPath' of undefined
    at atom-workspace.onSave (C:\Users\SWAKE\AppData\Local\learn_ide\app-2.1.0\resources\app.asar\node_modules\learn-ide-tree\lib\nsync\initializer.js:69:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\SWAKE\AppData\Local\learn_ide\app-2.1.0\resources\app.asar\src\command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (C:\Users\SWAKE\AppData\Local\learn_ide\app-2.1.0\resources\app.asar\src\command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\SWAKE\AppData\Local\learn_ide\app-2.1.0\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\SWAKE\AppData\Local\learn_ide\app-2.1.0\resources\app.asar\src\atom-environment.js:1136:28)
    at EventEmitter.outerCallback (C:\Users\SWAKE\AppData\Local\learn_ide\app-2.1.0\resources\app.asar\src\application-delegate.js:319:25)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

### Commands

```
  7x -9:53.4.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -9:47.3.0 learn-ide:save (atom-text-editor.editor.is-focused)
     -1:25.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:24.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:24.4.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:22.7.0 learn-ide:save (atom-text-editor.editor.is-focused)
     -1:11.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:03.7.0 learn-ide:save (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -0:37.9.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:32.3.0 learn-ide:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "integrated-learn-environment",
      "integrated-learn-environment",
      "tree-view",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment"
    ]
  }
}
```

### Installed Packages

```coffee
# User
integrated-learn-environment, vundefined (inactive)
learn-ide, v2.2.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.1 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
update-package-dependencies, v0.10.0 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)
learn-ide, v2.2.0 (active)
learn-ide-tree, v1.0.17 (active)

# Dev
No dev packages
```

**Comment by sjwakeman** [comment] 2016-12-29 22:30
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 2.1.0
**Electron Version**: 1.3.6
**System**: Microsoft Windows 10 Home
**Thrown From**: [learn-ide-tree](https://github.com/learn-co/learn-ide-tree) package, v1.0.17


### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At C:\Users\SWAKE\AppData\Local\learn_ide\app-2.1.0\resources\app.asar\node_modules\learn-ide-tree\lib\nsync\initializer.js:69

TypeError: Cannot read property 'getPath' of undefined
    at atom-workspace.onSave (C:\Users\SWAKE\AppData\Local\learn_ide\app-2.1.0\resources\app.asar\node_modules\learn-ide-tree\lib\nsync\initializer.js:69:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\SWAKE\AppData\Local\learn_ide\app-2.1.0\resources\app.asar\src\command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (C:\Users\SWAKE\AppData\Local\learn_ide\app-2.1.0\resources\app.asar\src\command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\SWAKE\AppData\Local\learn_ide\app-2.1.0\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\SWAKE\AppData\Local\learn_ide\app-2.1.0\resources\app.asar\src\atom-environment.js:1136:28)
    at EventEmitter.outerCallback (C:\Users\SWAKE\AppData\Local\learn_ide\app-2.1.0\resources\app.asar\src\application-delegate.js:319:25)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

### Commands

```
  2x -8:00.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -7:53.6.0 learn-ide:save (atom-text-editor.editor.is-focused)
     -7:09.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -7:06.5.0 learn-ide:save (atom-text-editor.editor.is-focused)
     -4:18.2.0 core:select-all (atom-text-editor.editor.is-focused)
     -4:17.1.0 core:copy (atom-text-editor.editor.is-focused)
  2x -0:52.3.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:30.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:27.9.0 learn-ide:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "integrated-learn-environment",
      "integrated-learn-environment",
      "tree-view",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment",
      "integrated-learn-environment"
    ]
  }
}
```

### Installed Packages

```coffee
# User
integrated-learn-environment, vundefined (inactive)
learn-ide, v2.2.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.1 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
update-package-dependencies, v0.10.0 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)
learn-ide, v2.2.0 (active)
learn-ide-tree, v1.0.17 (active)

# Dev
No dev packages
```

**Comment by aaronrtrevino12** [comment] 2016-12-29 23:32
Hey Scott,

Before I copied, pasted and posted the encountered errors, I typed up and
posted some steps.  Anyway, I've been working around the issue and have
gotten use to the errors.  Sometimes the errors (a red box) pops up when I
try to save the file (my code, for example: move.rb).  I sometimes have to
click on the "X" to close the file, then it may ask if I would like to
"Save".  I then click on "Save".  One time I clicked on "Save" and all my
code disappeared.  Good thing the "Undo" returned my code.  It was not a
pleasant moment.  Learn IDE works better when I use the "Open" button
within the labs, than when I open it from my desktop shortcut.  When I open
it from the desktop shortcut, it opens two windows which is better now
because it use to open three windows.  Anyway, not sure what you can do.
Thanks!

**Comment by sjwakeman** [comment] 2017-01-01 01:43
Aaron -
Thanks for the information. Regrettably nothing happens when I click on the "Open" button from the lesson on learn.co webpage. I can only open Atom from the shortcut on my desktop. The blue dot remains on the tab I am working on now. It use to go away after saving. However the code seems to save anyways. Guess will have to be patient as they look into this matter. I do encounter the same issue with the error report pop up only when I hit Ctrl+S or File > Save.
Thanks,
Scott

**Closed as completed** 2023-01-10 17:40 UTC
